from __future__ import annotations

from importlib.resources import as_file, files

from peval_py.html import ASSET_BUNDLES
from reports_html_support import *

class PevalPyReportHtmlAssetTokenTests(unittest.TestCase):
    def test_generated_report_js_has_valid_esm_syntax(self) -> None:
        node = shutil.which("node")
        if not node:
            self.skipTest("node is required for report JS syntax validation")
        asset_root = files("peval_py.assets")
        with as_file(asset_root.joinpath("report.js")) as path:
            result = subprocess.run(
                [node, "--check", str(path)],
                text=True,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
            )
        self.assertEqual(result.returncode, 0, result.stderr)

    def test_html_inlines_template_css_and_js_package_assets(self) -> None:
        report = {
            "schema_version": 19,
            "includes": ["core"],
            "trajectory": [
                {
                    "trajectory_id": "trial:assets",
                    "session_id": "assets",
                    "agent": {"name": "custom"},
                    "steps": [],
                    "final_metrics": {},
                }
            ],
            "trajectory_meta": [
                {
                    "trial_key": "trial:assets",
                    "status": "passed",
                    "steps": [],
                    "warnings": [],
                }
            ],
        }
        css = load_asset_text("report.css")
        js = load_asset_text("report.js")
        template = load_asset_text("report.html")
        html = render_html(report)
        compact_css = compact_css_text(css)

        def css_declarations(selector: str) -> set[str]:
            match = re.search(rf"{re.escape(selector)}\s*\{{([^}}]*)\}}", css)
            self.assertIsNotNone(match, f"missing CSS rule for {selector}")
            return {
                compact_css_text(declaration)
                for declaration in match.group(1).split(";")
                if declaration.strip()
            }

        self.assertIn("report_css/06-leaderboard-summary.css", ASSET_BUNDLES["report.css"])
        self.assertNotIn("report.js", ASSET_BUNDLES)
        self.assertTrue(js.startswith("// Generated by `npm run build`"))
        self.assertIn("__SERVE_SOURCE_MANAGER__", template)
        self.assertIn('<script type="application/json" id="peval-py-data">__DATA__</script>', template)
        self.assertIn('<script type="module">\n__JS__\n</script>', template)
        self.assertIn(".time-gradient", css)
        self.assertIn("flex-wrap:wrap", css)
        self.assertIn(".timeline-waterfall-shell", css)
        self.assertIn(".timeline-waterfall-chart", css)
        self.assertIn(".timeline-fallback", css)
        self.assertIn(".timeline-section", css)
        self.assertIn(".timeline-section-body", css)
        self.assertIn(".source-adapter-select", css)
        self.assertIn(".source-add-actions", css)
        self.assertIn("grid-template-columns:minmax(0,1fr)max-content", css_declarations(".db-path-control"))
        self.assertIn("grid-template-rows:repeat(2,minmax(0,1fr))", css_declarations(".db-default-actions"))
        self.assertIn(".source-form select", css)
        self.assertNotIn(".adapter-choice-group", css)
        for level in range(1, 11):
            self.assertIn(f".trajectory-node.duration-heat-{level}", css)
        self.assertIn("background:#d6a456", css)
        self.assertNotIn("background:#b88431", css)
        self.assertNotIn("background:#56380d", css)
        self.assertNotIn("color:#fff8ec", css)
        self.assertIn('.trajectory-node.selected-node[class*="duration-heat-"]', css)
        self.assertNotIn(".trajectory-node.time-gradient", css)
        self.assertNotIn(".trajectory-node.selected-node.time-gradient", css)
        self.assertNotIn("conic-gradient", css)
        self.assertIn(".serve-notice", css)
        self.assertIn(
            compact_css_text(
                ".timeline-section{display:grid;gap:10px;border:1px solid var(--rule);"
                "border-radius:var(--radius);background:transparent;padding:12px}"
            ),
            compact_css,
        )
        self.assertIn(
            compact_css_text(
                ".source-form{display:grid;gap:8px;border:1px solid var(--rule);"
                "border-radius:var(--radius);background:transparent;padding:12px}"
            ),
            compact_css,
        )
        self.assertIn("table-layout:auto", css)
        self.assertIn("min-width:max-content", css)
        self.assertIn(".leaderboard-summary-head", css)
        self.assertIn(".leaderboard-summary-table-toggle", css)
        self.assertIn(".leaderboard-summary-table", css)
        self.assertIn(".summary-metric-cell", css)
        self.assertIn(".summary-selected-stat", css)
        self.assertIn(".leaderboard-summary-chart-panel", css)
        self.assertIn(".leaderboard-summary-chart-grid", css)
        self.assertIn(".leaderboard-summary-bar", css)
        self.assertIn(".leaderboard-summary-bar-track", css)
        self.assertIn(".trajectory-row.trajectory-row-selectable", css)
        self.assertIn(".trajectory-select", css)
        self.assertIn(".source-state-controls", css)
        self.assertIn(".source-state-toggle", css)
        self.assertIn(".action-button", css)
        self.assertIn(".action-button.primary", css)
        self.assertIn("grid-row:2", css_declarations(".report-manager-status"))
        self.assertIn("grid-row:3", css_declarations(".report-manager-body"))
        self.assertNotIn(".leaderboard-summary-count", css)
        self.assertNotIn(".summary-boxplot", css)
        self.assertNotIn("--summary-whisker", css)
        self.assertIn(compact_css_text('[data-value-type="selection"]{width:46px'), compact_css)
        self.assertIn(compact_css_text('[data-value-type="number"]{--table-column-max:14ch}'), compact_css)
        self.assertIn(compact_css_text('[data-value-type="datetime"]'), compact_css)
        self.assertIn(compact_css_text('[data-value-type="status"]'), compact_css)
        self.assertIn(compact_css_text('[data-value-type="enum"]'), compact_css)
        self.assertIn("--table-column-max:20ch", compact_css)
        self.assertIn(compact_css_text('[data-value-type="text"]'), compact_css)
        self.assertIn(compact_css_text('[data-value-type="list"]'), compact_css)
        self.assertIn("--table-column-max:28ch", compact_css)
        self.assertIn(compact_css_text('[data-value-type="identity"]'), compact_css)
        self.assertIn(compact_css_text('[data-value-type="path"]'), compact_css)
        self.assertIn(compact_css_text('[data-value-type="markdown"]'), compact_css)
        self.assertIn(compact_css_text('[data-value-type="yaml"]'), compact_css)
        self.assertIn("--table-column-max:40ch", compact_css)
        self.assertIn("-webkit-line-clamp:2", compact_css)
        self.assertNotIn("max-width:260px", css_declarations(".data-table th,.data-table td"))
        self.assertNotIn("max-width:132px", css_declarations("td.num,th.num"))
        self.assertIn(".timeline-table td.metric-cell", css)
        self.assertIn(".timeline-table td.metric-cell.metric-shade-4", css)
        self.assertIn(
            compact_css_text(".timeline-detail-row{cursor:pointer}"),
            compact_css,
        )
        self.assertIn(
            compact_css_text(
                ".timeline-detail-selected td{background:color-mix(in oklch,var(--focus),#fff 92%)}"
            ),
            compact_css,
        )
        self.assertIn(
            compact_css_text(
                ".timeline-detail-selected td:first-child{box-shadow:inset 3px 0 0 var(--focus)}"
            ),
            compact_css,
        )
        self.assertNotIn(
            compact_css_text(
                ".timeline-detail-selected td{background:color-mix(in oklch,var(--focus),#fff 92%);box-shadow"
            ),
            compact_css,
        )
        self.assertIn(".timeline-stage-label", css)
        self.assertIn(".timeline-active-share", css)
        self.assertIn("--active-share-pct", css)
        self.assertIn('className: "active-share-cell"', js)
        self.assertIn(
            compact_css_text(
                ".timeline-category-external{background:#e2e8f0;color:#475569}"
            ),
            compact_css,
        )
        self.assertIn(
            compact_css_text(
                ".timeline-category-error{background:#fee2e2;color:#dc2626}"
            ),
            compact_css,
        )
        self.assertNotIn(".timeline-distribution", css)
        self.assertNotIn("table-layout:fixed", css)
        self.assertNotIn(".timeline-col-stage", css)
        self.assertNotIn(".timeline-category-chip", css)
        self.assertNotIn(".timeline-category-external,.timeline-category-error", css)
        self.assertNotIn(".timeline-category-idle", css)
        self.assertNotIn(".timeline-waterfall-svg", css)
        self.assertIn('"peval-py-entrypoint";', js)
        self.assertIn("<style>\n:root", html)
        self.assertIn(
            "https://cdn.jsdelivr.net/npm/echarts@6.0.0/dist/echarts.min.js",
            html,
        )
        self.assertIn('<script type="module">', html)
        self.assertIn('id="leaderboard-summary"', html)
        self.assertIn("// Generated by `npm run build`", html)
        self.assertIn('<script type="application/json" id="peval-py-data">', html)
        self.assertNotIn("__SERVE_SOURCE_MANAGER__", html)
        self.assertNotIn("__DATA__", html)
        self.assertNotIn("__CSS__", html)
        self.assertNotIn("__JS__", html)


    def test_html_timing_gradients_ignore_missing_values_without_mutating_report(self) -> None:
        report = {
            "schema_version": 19,
            "includes": ["core"],
            "trajectory": [
                {
                    "trajectory_id": "trial:missing-time",
                    "session_id": "missing-time",
                    "agent": {"name": "custom"},
                    "steps": [
                        {
                            "step_id": 1,
                            "source": "agent",
                            "message": "no timing",
                            "tool_calls": [
                                {
                                    "tool_call_id": "call-1",
                                    "function_name": "exec_command",
                                    "arguments": {"cmd": "true"},
                                }
                            ],
                        }
                    ],
                    "final_metrics": {},
                }
            ],
            "trajectory_meta": [
                {
                    "trial_key": "trial:missing-time",
                    "status": "passed",
                    "steps": [
                        {
                            "step_id": 1,
                            "duration_ms": 0,
                            "elapsed_ms": None,
                            "tool_calls": [
                                {
                                    "tool_call_id": "call-1",
                                    "title": "exec_command",
                                    "execution_duration_ms": None,
                                }
                            ],
                        }
                    ],
                    "warnings": [],
                }
            ],
        }
        before = json.loads(json.dumps(report))
        html = render_html(report)
        payload = script_json(html, "peval-py-data")

        self.assertEqual(report, before)
        self.assertEqual(payload, before)
        self.assertIn("function positiveMetric", html)
        self.assertIn("if (!positiveMetric(value) || !positiveMetric(max)) return null", html)


    def test_html_estimates_missing_step_token_chips_without_mutating_report(self) -> None:
        report = {
            "schema_version": 19,
            "includes": ["core"],
            "trajectory": [
                {
                    "trajectory_id": "trial:estimate",
                    "session_id": "estimate-session",
                    "agent": {"name": "custom", "model_name": "unknown-model"},
                    "steps": [
                        {
                            "step_id": 1,
                            "source": "agent",
                            "message": "abcdefgh",
                            "tool_calls": [
                                {
                                    "tool_call_id": "call-1",
                                    "function_name": "read",
                                    "arguments": {"path": "README.md"},
                                }
                            ],
                        }
                    ],
                    "final_metrics": {"total_prompt_tokens": 100},
                }
            ],
            "trajectory_meta": [
                {
                    "trial_key": "trial:estimate",
                    "status": "passed",
                    "steps": [{"step_id": 1, "duration_ms": None}],
                    "warnings": [],
                }
            ],
        }
        before = json.loads(json.dumps(report))
        with patch("peval_py.html.import_module", side_effect=ImportError("missing")):
            html = render_html(report)

        self.assertEqual(report, before)
        estimates = script_json(html, "peval-py-token-estimates")
        self.assertIn("trial:estimate", estimates)
        estimate = estimates["trial:estimate"]["1"]
        self.assertEqual(estimate["method"], "byte_length_div_4")
        self.assertEqual(estimate["source"], "visible_step_text")
        self.assertTrue(estimate["estimated"])
        self.assertGreater(estimate["tokens"], 0)
        self.assertIn("renderStepRail(step, sm, meta?.trial_key, timingStats)", html)
        self.assertIn("stepTokenInfo(step, trialKey)", html)
        self.assertIn("stepTokenEstimate(trialKey, step.step_id)", html)
        self.assertIn("estimated tokens", html)
        self.assertIn("from visible step text", html)
        self.assertIn("≈", html)
        self.assertNotIn("estimated", script_json(html, "peval-py-data")["trajectory"][0]["steps"][0])


    def test_html_preserves_exact_step_tokens_without_estimate(self) -> None:
        report = {
            "schema_version": 19,
            "includes": ["core"],
            "trajectory": [
                {
                    "trajectory_id": "trial:exact",
                    "session_id": "exact-session",
                    "agent": {"name": "custom", "model_name": "unknown-model"},
                    "steps": [
                        {
                            "step_id": 1,
                            "source": "agent",
                            "message": "abcdefgh",
                            "metrics": {"prompt_tokens": 3, "completion_tokens": 4},
                        }
                    ],
                    "final_metrics": {"total_prompt_tokens": 3, "total_completion_tokens": 4},
                }
            ],
            "trajectory_meta": [
                {
                    "trial_key": "trial:exact",
                    "status": "passed",
                    "steps": [{"step_id": 1, "duration_ms": None}],
                    "warnings": [],
                }
            ],
        }
        with patch("peval_py.html.import_module", side_effect=ImportError("missing")):
            html = render_html(report)

        self.assertEqual(script_json(html, "peval-py-token-estimates"), {})
        payload = script_json(html, "peval-py-data")
        self.assertEqual(payload["trajectory"][0]["steps"][0]["metrics"]["prompt_tokens"], 3)


    def test_html_estimated_tokens_can_use_optional_tiktoken(self) -> None:
        class FakeEncoding:
            name = "fake-model-encoding"

            def encode(self, text: str):
                return list(range(7))

        class FakeTiktoken:
            def encoding_for_model(self, model: str):
                self.model = model
                return FakeEncoding()

            def get_encoding(self, name: str):
                raise AssertionError("model encoding should be used")

        report = {
            "schema_version": 19,
            "includes": ["core"],
            "trajectory": [
                {
                    "trajectory_id": "trial:tiktoken",
                    "session_id": "tiktoken-session",
                    "agent": {"name": "custom", "model_name": "fake-model"},
                    "steps": [
                        {
                            "step_id": 1,
                            "source": "agent",
                            "message": "model counted text",
                        }
                    ],
                    "final_metrics": {},
                }
            ],
            "trajectory_meta": [
                {
                    "trial_key": "trial:tiktoken",
                    "status": "passed",
                    "steps": [{"step_id": 1, "duration_ms": None}],
                    "warnings": [],
                }
            ],
        }
        fake = FakeTiktoken()
        with patch("peval_py.html.import_module", return_value=fake):
            html = render_html(report)

        self.assertEqual(fake.model, "fake-model")
        estimate = script_json(html, "peval-py-token-estimates")["trial:tiktoken"]["1"]
        self.assertEqual(estimate["tokens"], 7)
        self.assertEqual(estimate["method"], "tiktoken:fake-model-encoding")
